use chrono::{DateTime, Utc};
use serde::{Deserialize, Serialize};
use std::collections::HashMap;
use std::net::IpAddr;
use uuid::Uuid;

/// IDS operating mode
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
#[derive(Default)]
pub enum IdsMode {
    /// Alert only — log detections, never block
    Ids,
    /// Inline — drop/reject packets matching drop rules
    Ips,
    /// Engine disabled
    #[default]
    Disabled,
}

impl std::fmt::Display for IdsMode {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            Self::Ids => write!(f, "ids"),
            Self::Ips => write!(f, "ips"),
            Self::Disabled => write!(f, "disabled"),
        }
    }
}

/// Severity levels (1 = critical, 4 = informational)
#[derive(Debug, Clone, Copy, PartialEq, Eq, PartialOrd, Ord, Serialize, Deserialize)]
pub struct IdsSeverity(pub u8);

impl IdsSeverity {
    pub const CRITICAL: Self = Self(1);
    pub const HIGH: Self = Self(2);
    pub const MEDIUM: Self = Self(3);
    pub const INFO: Self = Self(4);

    pub fn label(&self) -> &'static str {
        match self.0 {
            1 => "critical",
            2 => "high",
            3 => "medium",
            _ => "info",
        }
    }
}

impl Default for IdsSeverity {
    fn default() -> Self {
        Self::MEDIUM
    }
}

/// Source format of an IDS rule
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum RuleFormat {
    Suricata,
    Sigma,
    Yara,
}

impl std::fmt::Display for RuleFormat {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            Self::Suricata => write!(f, "suricata"),
            Self::Sigma => write!(f, "sigma"),
            Self::Yara => write!(f, "yara"),
        }
    }
}

impl RuleFormat {
    pub fn from_str(s: &str) -> Option<Self> {
        match s {
            "suricata" => Some(Self::Suricata),
            "sigma" => Some(Self::Sigma),
            "yara" => Some(Self::Yara),
            _ => None,
        }
    }
}

/// Where the rule originated
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum RuleSource {
    EtOpen,
    Sigma,
    Yara,
    Custom,
}

impl std::fmt::Display for RuleSource {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            Self::EtOpen => write!(f, "et_open"),
            Self::Sigma => write!(f, "sigma"),
            Self::Yara => write!(f, "yara"),
            Self::Custom => write!(f, "custom"),
        }
    }
}

impl RuleSource {
    pub fn from_str(s: &str) -> Option<Self> {
        match s {
            "et_open" => Some(Self::EtOpen),
            "sigma" => Some(Self::Sigma),
            "yara" => Some(Self::Yara),
            "custom" => Some(Self::Custom),
            _ => None,
        }
    }
}

/// Action for an IDS rule verdict
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum IdsAction {
    Alert,
    Drop,
    Reject,
    Pass,
}

impl std::fmt::Display for IdsAction {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            Self::Alert => write!(f, "alert"),
            Self::Drop => write!(f, "drop"),
            Self::Reject => write!(f, "reject"),
            Self::Pass => write!(f, "pass"),
        }
    }
}

impl IdsAction {
    pub fn from_str(s: &str) -> Option<Self> {
        match s {
            "alert" => Some(Self::Alert),
            "drop" => Some(Self::Drop),
            "reject" => Some(Self::Reject),
            "pass" => Some(Self::Pass),
            _ => None,
        }
    }
}

/// An alert generated by the IDS engine
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct IdsAlert {
    pub id: Uuid,
    pub timestamp: DateTime<Utc>,
    pub signature_id: Option<u32>,
    pub signature_msg: String,
    pub severity: IdsSeverity,
    pub src_ip: IpAddr,
    pub src_port: Option<u16>,
    pub dst_ip: IpAddr,
    pub dst_port: Option<u16>,
    pub protocol: String,
    pub action: IdsAction,
    pub rule_source: RuleSource,
    pub flow_id: Option<String>,
    pub payload_excerpt: Option<String>,
    pub metadata: Option<HashMap<String, String>>,
    pub acknowledged: bool,
    /// Classification: unreviewed, confirmed, false_positive, investigating
    #[serde(default = "default_classification")]
    pub classification: String,
    /// Free-form analyst notes
    pub analyst_notes: Option<String>,
}

fn default_classification() -> String {
    "unreviewed".to_string()
}

impl IdsAlert {
    pub fn new(
        signature_msg: String,
        severity: IdsSeverity,
        src_ip: IpAddr,
        dst_ip: IpAddr,
        protocol: &str,
        action: IdsAction,
        rule_source: RuleSource,
    ) -> Self {
        Self {
            id: Uuid::new_v4(),
            timestamp: Utc::now(),
            signature_id: None,
            signature_msg,
            severity,
            src_ip,
            src_port: None,
            dst_ip,
            dst_port: None,
            protocol: protocol.to_string(),
            action,
            rule_source,
            flow_id: None,
            payload_excerpt: None,
            metadata: None,
            acknowledged: false,
            classification: "unreviewed".to_string(),
            analyst_notes: None,
        }
    }
}

/// A configured ruleset (ET Open, Sigma community, YARA rules, etc.)
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct IdsRuleset {
    pub id: Uuid,
    pub name: String,
    pub source_url: Option<String>,
    pub rule_format: RuleFormat,
    pub enabled: bool,
    pub auto_update: bool,
    pub update_interval_hours: u32,
    pub last_updated: Option<DateTime<Utc>>,
    pub rule_count: u32,
    pub created_at: DateTime<Utc>,
}

/// A single IDS rule from a ruleset
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct IdsRule {
    pub id: Uuid,
    pub ruleset_id: Uuid,
    pub sid: Option<u32>,
    pub rule_text: String,
    pub msg: Option<String>,
    pub severity: IdsSeverity,
    pub enabled: bool,
    pub action_override: Option<IdsAction>,
    pub hit_count: u64,
    pub last_hit: Option<DateTime<Utc>>,
    pub created_at: DateTime<Utc>,
}

/// IDS engine configuration
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct IdsConfig {
    pub mode: IdsMode,
    pub home_net: Vec<String>,
    pub external_net: Vec<String>,
    pub interfaces: Vec<String>,
    pub alert_retention_days: u32,
    pub eve_log_enabled: bool,
    pub eve_log_path: Option<String>,
    pub syslog_target: Option<String>,
    pub worker_count: Option<u32>,
    pub flow_table_size: Option<u32>,
    pub stream_depth: Option<u32>,
    /// Per-direction stream reassembly depth, in KB. `None` = built-in default (64 KB).
    pub flow_stream_depth_kb: Option<u32>,
}

impl Default for IdsConfig {
    fn default() -> Self {
        Self {
            mode: IdsMode::Disabled,
            home_net: vec![
                "10.0.0.0/8".into(),
                "172.16.0.0/12".into(),
                "192.168.0.0/16".into(),
            ],
            external_net: vec!["!$HOME_NET".into()],
            interfaces: Vec::new(),
            alert_retention_days: 30,
            eve_log_enabled: false,
            eve_log_path: None,
            syslog_target: None,
            worker_count: None,
            flow_table_size: None,
            stream_depth: None,
            flow_stream_depth_kb: None,
        }
    }
}

/// Real-time IDS engine statistics
#[derive(Debug, Clone, Default, Serialize, Deserialize)]
pub struct IdsStats {
    pub packets_inspected: u64,
    pub alerts_total: u64,
    pub drops_total: u64,
    pub bytes_per_sec: f64,
    pub packets_per_sec: f64,
    pub active_flows: u64,
    pub uptime_secs: u64,
}

/// A suppression silences a specific rule for a given IP/subnet
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct IdsSuppression {
    pub id: Uuid,
    pub sid: u32,
    pub suppress_type: SuppressType,
    pub ip_cidr: Option<String>,
    pub created_at: DateTime<Utc>,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum SuppressType {
    Src,
    Dst,
    Both,
}

impl std::fmt::Display for SuppressType {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            Self::Src => write!(f, "src"),
            Self::Dst => write!(f, "dst"),
            Self::Both => write!(f, "both"),
        }
    }
}

impl SuppressType {
    pub fn from_str(s: &str) -> Option<Self> {
        match s {
            "src" => Some(Self::Src),
            "dst" => Some(Self::Dst),
            "both" => Some(Self::Both),
            _ => None,
        }
    }
}

/// Result of matching a rule against a packet/flow
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct IdsRuleMatch {
    pub rule_id: String,
    pub sid: Option<u32>,
    pub msg: String,
    pub severity: IdsSeverity,
    pub source: RuleSource,
    pub action: IdsAction,
    pub metadata: HashMap<String, String>,
}
