use crate::types::{Address, Interface};
use chrono::{DateTime, Utc};
use serde::{Deserialize, Serialize};
use uuid::Uuid;

// ============================================================
// WireGuard
// ============================================================

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct WgTunnel {
    pub id: Uuid,
    pub name: String,
    pub interface: Interface,
    pub private_key: String,
    pub public_key: String,
    pub listen_port: u16,
    pub address: Address,
    pub dns: Option<String>,
    pub mtu: Option<u16>,
    /// Physical interface to listen on (e.g. "vtnet0"). None = listen on all.
    pub listen_interface: Option<String>,
    /// Comma-separated CIDRs to route through the tunnel when a client uses
    /// split-tunnel mode (e.g. `172.29.0.0/16, 10.0.0.0/8`). When `None`, the
    /// split-tunnel config falls back to the tunnel's own network CIDR.
    #[serde(default)]
    pub split_routes: Option<String>,
    pub status: VpnStatus,
    pub created_at: DateTime<Utc>,
    pub updated_at: DateTime<Utc>,
}

impl WgTunnel {
    pub fn new(name: String, interface: Interface, listen_port: u16, address: Address) -> Self {
        let (private_key, public_key) = generate_wg_keypair();
        let now = Utc::now();
        Self {
            id: Uuid::new_v4(),
            name,
            interface,
            private_key,
            public_key,
            listen_port,
            address,
            dns: None,
            mtu: None,
            listen_interface: None,
            split_routes: None,
            status: VpnStatus::Down,
            created_at: now,
            updated_at: now,
        }
    }

    /// Generate ifconfig commands to create the WireGuard interface
    pub fn to_ifconfig_cmds(&self) -> Vec<String> {
        let mut cmds = vec![
            format!("ifconfig {} create", self.interface),
            format!("ifconfig {} inet {} up", self.interface, self.address),
        ];
        if let Some(mtu) = self.mtu {
            cmds.push(format!("ifconfig {} mtu {mtu}", self.interface));
        }
        cmds
    }

    /// Generate pf rules to allow WireGuard traffic
    pub fn to_pf_rules(&self) -> Vec<String> {
        // If listen_interface is set, bind the UDP rule to that interface
        let on_iface = match &self.listen_interface {
            Some(iface) if !iface.is_empty() && iface != "any" => format!(" on {iface}"),
            _ => String::new(),
        };
        vec![
            // Allow WireGuard UDP port (optionally on specific interface)
            format!(
                "pass in quick{on_iface} proto udp to any port {} keep state label \"wg-{}\"",
                self.listen_port, self.name
            ),
            // Allow all traffic on the WireGuard tunnel interface (flags any = ICMP/UDP too)
            format!(
                "pass quick on {} flags any keep state label \"wg-{}-tunnel\"",
                self.interface, self.name
            ),
        ]
    }
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct WgPeer {
    pub id: Uuid,
    pub tunnel_id: Uuid,
    pub name: String,
    pub public_key: String,
    pub preshared_key: Option<String>,
    /// Client private key — stored so we can generate the client config.
    /// Only present when the keypair was auto-generated by the server.
    pub client_private_key: Option<String>,
    pub endpoint: Option<String>,
    pub allowed_ips: Vec<Address>,
    pub persistent_keepalive: Option<u16>,
    pub created_at: DateTime<Utc>,
    pub updated_at: DateTime<Utc>,
}

impl WgPeer {
    pub fn new(tunnel_id: Uuid, name: String, public_key: String) -> Self {
        let now = Utc::now();
        Self {
            id: Uuid::new_v4(),
            tunnel_id,
            name,
            public_key,
            preshared_key: None,
            client_private_key: None,
            endpoint: None,
            allowed_ips: vec![Address::Any],
            persistent_keepalive: None,
            created_at: now,
            updated_at: now,
        }
    }

    /// Create a peer with an auto-generated keypair (private key stored for config export).
    pub fn new_with_generated_key(tunnel_id: Uuid, name: String) -> Self {
        let (private_key, public_key) = generate_wg_keypair();
        let mut peer = Self::new(tunnel_id, name, public_key);
        peer.client_private_key = Some(private_key);
        peer
    }

    /// Generate a WireGuard client .conf file for this peer.
    /// `tunnel` is the server-side tunnel this peer belongs to.
    /// `server_endpoint` is the firewall's public IP or hostname.
    /// `split_tunnel` — if true, only routes the tunnel subnet through the VPN (split VPN).
    ///                   if false, routes all traffic through the VPN (full tunnel).
    pub fn to_client_config(
        &self,
        tunnel: &WgTunnel,
        server_endpoint: &str,
        split_tunnel: bool,
    ) -> String {
        let mut conf = String::from("[Interface]\n");
        if let Some(ref pk) = self.client_private_key {
            conf.push_str(&format!("PrivateKey = {pk}\n"));
        } else {
            conf.push_str("PrivateKey = <paste-your-private-key-here>\n");
        }
        // Use the first allowed_ip as the client's address
        if let Some(addr) = self.allowed_ips.first() {
            conf.push_str(&format!("Address = {addr}\n"));
        }
        if let Some(ref dns) = tunnel.dns
            && !dns.is_empty()
        {
            conf.push_str(&format!("DNS = {dns}\n"));
        }
        if let Some(mtu) = tunnel.mtu {
            conf.push_str(&format!("MTU = {mtu}\n"));
        }
        conf.push_str(&format!("\n[Peer]\nPublicKey = {}\n", tunnel.public_key));
        if let Some(ref psk) = self.preshared_key {
            conf.push_str(&format!("PresharedKey = {psk}\n"));
        }
        conf.push_str(&format!(
            "Endpoint = {server_endpoint}:{}\n",
            tunnel.listen_port
        ));
        if split_tunnel {
            // Prefer admin-configured split routes; otherwise derive the
            // network CIDR from the tunnel address (so 172.29.240.1/24 yields
            // 172.29.240.0/24 instead of a host/prefix that confuses some
            // clients).
            let routes = tunnel
                .split_routes
                .as_deref()
                .map(|s| s.trim())
                .filter(|s| !s.is_empty())
                .map(|s| s.to_string())
                .unwrap_or_else(|| address_network_cidr(&tunnel.address));
            conf.push_str(&format!("AllowedIPs = {routes}\n"));
        } else {
            // Route all traffic through the VPN
            conf.push_str("AllowedIPs = 0.0.0.0/0, ::/0\n");
        }
        if let Some(ka) = self.persistent_keepalive {
            conf.push_str(&format!("PersistentKeepalive = {ka}\n"));
        }
        conf
    }

    /// Generate wg set command for this peer
    pub fn to_wg_cmd(&self, iface: &Interface) -> String {
        let mut parts = vec![format!("wg set {} peer {}", iface, self.public_key)];

        if let Some(ref endpoint) = self.endpoint {
            parts.push(format!("endpoint {endpoint}"));
        }

        let allowed: Vec<String> = self.allowed_ips.iter().map(|a| a.to_string()).collect();
        if !allowed.is_empty() {
            parts.push(format!("allowed-ips {}", allowed.join(",")));
        }

        if let Some(ka) = self.persistent_keepalive {
            parts.push(format!("persistent-keepalive {ka}"));
        }

        if let Some(ref psk) = self.preshared_key {
            parts.push(format!("preshared-key {psk}"));
        }

        parts.join(" ")
    }
}

// ============================================================
// IPsec
// ============================================================

#[derive(Debug, Clone, Copy, Serialize, Deserialize, PartialEq, Eq)]
#[serde(rename_all = "snake_case")]
pub enum IpsecProtocol {
    Esp,
    Ah,
    EspAh,
}

impl std::fmt::Display for IpsecProtocol {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            IpsecProtocol::Esp => write!(f, "esp"),
            IpsecProtocol::Ah => write!(f, "ah"),
            IpsecProtocol::EspAh => write!(f, "esp+ah"),
        }
    }
}

impl IpsecProtocol {
    pub fn parse(s: &str) -> crate::Result<Self> {
        match s.to_lowercase().as_str() {
            "esp" => Ok(IpsecProtocol::Esp),
            "ah" => Ok(IpsecProtocol::Ah),
            "esp+ah" | "espah" | "esp_ah" => Ok(IpsecProtocol::EspAh),
            _ => Err(crate::AifwError::Validation(format!(
                "unknown IPsec protocol: {s}"
            ))),
        }
    }
}

#[derive(Debug, Clone, Copy, Serialize, Deserialize, PartialEq, Eq)]
#[serde(rename_all = "snake_case")]
pub enum IpsecMode {
    Tunnel,
    Transport,
}

impl std::fmt::Display for IpsecMode {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            IpsecMode::Tunnel => write!(f, "tunnel"),
            IpsecMode::Transport => write!(f, "transport"),
        }
    }
}

/// IPsec Security Association
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct IpsecSa {
    pub id: Uuid,
    pub name: String,
    pub src_addr: Address,
    pub dst_addr: Address,
    pub protocol: IpsecProtocol,
    pub mode: IpsecMode,
    pub spi: u32,
    pub enc_algo: String,
    pub auth_algo: String,
    pub status: VpnStatus,
    pub created_at: DateTime<Utc>,
    pub updated_at: DateTime<Utc>,
}

impl IpsecSa {
    pub fn new(
        name: String,
        src_addr: Address,
        dst_addr: Address,
        protocol: IpsecProtocol,
        mode: IpsecMode,
    ) -> Self {
        let now = Utc::now();
        Self {
            id: Uuid::new_v4(),
            name,
            src_addr,
            dst_addr,
            protocol,
            mode,
            spi: rand_spi(),
            enc_algo: "aes-256-gcm".to_string(),
            auth_algo: "hmac-sha256".to_string(),
            status: VpnStatus::Down,
            created_at: now,
            updated_at: now,
        }
    }

    /// Generate pf rules for IPsec traffic
    pub fn to_pf_rules(&self) -> Vec<String> {
        let proto = match self.protocol {
            IpsecProtocol::Esp | IpsecProtocol::EspAh => "esp",
            IpsecProtocol::Ah => "ah",
        };

        let mut rules = vec![
            // Allow IPsec protocol traffic between endpoints
            format!(
                "pass in quick proto {} from {} to {} keep state label \"ipsec-{}-in\"",
                proto, self.src_addr, self.dst_addr, self.name
            ),
            format!(
                "pass out quick proto {} from {} to {} keep state label \"ipsec-{}-out\"",
                proto, self.dst_addr, self.src_addr, self.name
            ),
            // Allow IKE (UDP 500 + 4500)
            format!(
                "pass in quick proto udp from {} to {} port {{ 500 4500 }} keep state label \"ike-{}-in\"",
                self.src_addr, self.dst_addr, self.name
            ),
            format!(
                "pass out quick proto udp from {} to {} port {{ 500 4500 }} keep state label \"ike-{}-out\"",
                self.dst_addr, self.src_addr, self.name
            ),
        ];

        // If tunnel mode, also allow enc0 traffic
        if self.mode == IpsecMode::Tunnel {
            rules.push(format!(
                "pass quick on enc0 keep state label \"ipsec-{}-tunnel\"",
                self.name
            ));
        }

        rules
    }
}

/// IPsec Security Policy
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct IpsecSp {
    pub id: Uuid,
    pub sa_id: Uuid,
    pub direction: SpDirection,
    pub src_network: Address,
    pub dst_network: Address,
    pub protocol: IpsecProtocol,
    pub mode: IpsecMode,
    pub level: SpLevel,
    pub created_at: DateTime<Utc>,
}

#[derive(Debug, Clone, Copy, Serialize, Deserialize, PartialEq, Eq)]
#[serde(rename_all = "lowercase")]
pub enum SpDirection {
    In,
    Out,
}

impl std::fmt::Display for SpDirection {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            SpDirection::In => write!(f, "in"),
            SpDirection::Out => write!(f, "out"),
        }
    }
}

#[derive(Debug, Clone, Copy, Serialize, Deserialize, PartialEq, Eq)]
#[serde(rename_all = "lowercase")]
pub enum SpLevel {
    Require,
    Use,
    Unique,
}

impl std::fmt::Display for SpLevel {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            SpLevel::Require => write!(f, "require"),
            SpLevel::Use => write!(f, "use"),
            SpLevel::Unique => write!(f, "unique"),
        }
    }
}

impl IpsecSp {
    pub fn new(
        sa_id: Uuid,
        direction: SpDirection,
        src_network: Address,
        dst_network: Address,
        protocol: IpsecProtocol,
        mode: IpsecMode,
    ) -> Self {
        Self {
            id: Uuid::new_v4(),
            sa_id,
            direction,
            src_network,
            dst_network,
            protocol,
            mode,
            level: SpLevel::Require,
            created_at: Utc::now(),
        }
    }

    /// Generate setkey policy line
    pub fn to_setkey_cmd(&self) -> String {
        format!(
            "spdadd {} {} any -P {} ipsec {}/{}/{}/{}",
            self.src_network,
            self.dst_network,
            self.direction,
            self.protocol,
            self.mode,
            self.src_network,
            self.level,
        )
    }
}

// ============================================================
// Common VPN types
// ============================================================

#[derive(Debug, Clone, Copy, Serialize, Deserialize, PartialEq, Eq)]
#[serde(rename_all = "lowercase")]
pub enum VpnStatus {
    Up,
    Down,
    Error,
}

impl std::fmt::Display for VpnStatus {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            VpnStatus::Up => write!(f, "up"),
            VpnStatus::Down => write!(f, "down"),
            VpnStatus::Error => write!(f, "error"),
        }
    }
}

#[derive(Debug, Clone, Copy, Serialize, Deserialize, PartialEq, Eq)]
#[serde(rename_all = "lowercase")]
pub enum VpnType {
    WireGuard,
    Ipsec,
}

impl std::fmt::Display for VpnType {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            VpnType::WireGuard => write!(f, "wireguard"),
            VpnType::Ipsec => write!(f, "ipsec"),
        }
    }
}

// ============================================================
// Key generation helpers (mock for non-FreeBSD)
// ============================================================

/// Generate a WireGuard keypair (32 random bytes each, base64 encoded).
/// On FreeBSD with wireguard-tools, uses `wg genkey` + `wg pubkey` for real Curve25519 keys.
/// Elsewhere, generates random 32-byte keys (valid format but not cryptographically derived).
pub fn generate_wg_keypair() -> (String, String) {
    // Try wg genkey first (FreeBSD with wireguard-tools installed)
    if let Ok(output) = std::process::Command::new("wg").arg("genkey").output()
        && output.status.success()
    {
        let privkey = String::from_utf8_lossy(&output.stdout).trim().to_string();
        if privkey.len() >= 40 {
            // Derive public key from private key
            if let Ok(pub_output) = std::process::Command::new("wg")
                .arg("pubkey")
                .stdin(std::process::Stdio::piped())
                .stdout(std::process::Stdio::piped())
                .spawn()
                .and_then(|mut child| {
                    use std::io::Write;
                    if let Some(ref mut stdin) = child.stdin {
                        let _ = stdin.write_all(privkey.as_bytes());
                    }
                    child.wait_with_output()
                })
                && pub_output.status.success()
            {
                let pubkey = String::from_utf8_lossy(&pub_output.stdout)
                    .trim()
                    .to_string();
                if pubkey.len() >= 40 {
                    return (privkey, pubkey);
                }
            }
        }
    }

    // Fallback: generate 32 random bytes for each key
    let mut private_bytes = [0u8; 32];
    let mut public_bytes = [0u8; 32];
    let id1 = Uuid::new_v4();
    let id2 = Uuid::new_v4();
    private_bytes[..16].copy_from_slice(id1.as_bytes());
    private_bytes[16..].copy_from_slice(id2.as_bytes());
    let id3 = Uuid::new_v4();
    let id4 = Uuid::new_v4();
    public_bytes[..16].copy_from_slice(id3.as_bytes());
    public_bytes[16..].copy_from_slice(id4.as_bytes());
    (base64_encode(&private_bytes), base64_encode(&public_bytes))
}

/// Generate a WireGuard preshared key (32 random bytes, base64 encoded)
pub fn generate_wg_psk() -> String {
    // Try wg genpsk first
    if let Ok(output) = std::process::Command::new("wg").arg("genpsk").output()
        && output.status.success()
    {
        let psk = String::from_utf8_lossy(&output.stdout).trim().to_string();
        if psk.len() >= 40 {
            return psk;
        }
    }
    let mut bytes = [0u8; 32];
    let id1 = Uuid::new_v4();
    let id2 = Uuid::new_v4();
    bytes[..16].copy_from_slice(id1.as_bytes());
    bytes[16..].copy_from_slice(id2.as_bytes());
    base64_encode(&bytes)
}

fn base64_encode(data: &[u8]) -> String {
    use std::fmt::Write;
    const CHARS: &[u8] = b"ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/";
    let mut result = String::new();
    for chunk in data.chunks(3) {
        let b0 = chunk[0] as u32;
        let b1 = chunk.get(1).copied().unwrap_or(0) as u32;
        let b2 = chunk.get(2).copied().unwrap_or(0) as u32;
        let triple = (b0 << 16) | (b1 << 8) | b2;
        let _ = write!(
            result,
            "{}",
            CHARS[((triple >> 18) & 0x3F) as usize] as char
        );
        let _ = write!(
            result,
            "{}",
            CHARS[((triple >> 12) & 0x3F) as usize] as char
        );
        if chunk.len() > 1 {
            let _ = write!(result, "{}", CHARS[((triple >> 6) & 0x3F) as usize] as char);
        } else {
            result.push('=');
        }
        if chunk.len() > 2 {
            let _ = write!(result, "{}", CHARS[(triple & 0x3F) as usize] as char);
        } else {
            result.push('=');
        }
    }
    result
}

/// Generate a random SPI value for IPsec
fn rand_spi() -> u32 {
    let id = Uuid::new_v4();
    let bytes = id.as_bytes();
    u32::from_be_bytes([bytes[0], bytes[1], bytes[2], bytes[3]]) | 0x100
}

/// Turn an Address into a WireGuard-friendly network CIDR string.
/// `Address::Network(172.29.240.1, 24)` → `"172.29.240.0/24"` (masked to the
/// network boundary). Falls back to "0.0.0.0/0" for non-network variants.
fn address_network_cidr(addr: &crate::types::Address) -> String {
    use crate::types::Address;
    use std::net::IpAddr;
    match addr {
        Address::Network(ip, prefix) => match ip {
            IpAddr::V4(v4) => {
                let p = (*prefix).min(32);
                let bits = u32::from(*v4);
                let mask: u32 = if p == 0 { 0 } else { u32::MAX << (32 - p) };
                let net = std::net::Ipv4Addr::from(bits & mask);
                format!("{net}/{p}")
            }
            IpAddr::V6(v6) => {
                let p = (*prefix).min(128);
                let bits = u128::from(*v6);
                let mask: u128 = if p == 0 { 0 } else { u128::MAX << (128 - p) };
                let net = std::net::Ipv6Addr::from(bits & mask);
                format!("{net}/{p}")
            }
        },
        Address::Single(ip) => match ip {
            IpAddr::V4(_) => format!("{ip}/32"),
            IpAddr::V6(_) => format!("{ip}/128"),
        },
        _ => "0.0.0.0/0".to_string(),
    }
}

#[cfg(test)]
mod split_tunnel_tests {
    use super::*;
    use crate::types::Address;

    #[test]
    fn network_cidr_masks_to_boundary() {
        let a = Address::Network("172.29.240.1".parse().unwrap(), 24);
        assert_eq!(address_network_cidr(&a), "172.29.240.0/24");
    }

    #[test]
    fn network_cidr_handles_slash_16() {
        let a = Address::Network("172.29.5.1".parse().unwrap(), 16);
        assert_eq!(address_network_cidr(&a), "172.29.0.0/16");
    }

    #[test]
    fn single_address_becomes_host_route() {
        let a = Address::Single("10.0.0.1".parse().unwrap());
        assert_eq!(address_network_cidr(&a), "10.0.0.1/32");
    }

    #[test]
    fn split_routes_override_wins() {
        let tunnel = WgTunnel {
            id: Uuid::new_v4(),
            name: "wg0".into(),
            interface: crate::types::Interface("wg0".into()),
            private_key: "x".into(),
            public_key: "y".into(),
            listen_port: 51820,
            address: Address::Network("172.29.240.1".parse().unwrap(), 24),
            dns: None,
            mtu: None,
            listen_interface: None,
            split_routes: Some("172.29.0.0/16, 10.0.0.0/8".into()),
            status: VpnStatus::Down,
            created_at: Utc::now(),
            updated_at: Utc::now(),
        };
        let peer = WgPeer {
            id: Uuid::new_v4(),
            tunnel_id: tunnel.id,
            name: "peer1".into(),
            public_key: "pk".into(),
            preshared_key: None,
            client_private_key: Some("cpk".into()),
            endpoint: None,
            allowed_ips: vec![Address::Network("172.29.240.2".parse().unwrap(), 32)],
            persistent_keepalive: None,
            created_at: Utc::now(),
            updated_at: Utc::now(),
        };
        let cfg = peer.to_client_config(&tunnel, "1.2.3.4", true);
        assert!(cfg.contains("AllowedIPs = 172.29.0.0/16, 10.0.0.0/8"));
    }

    #[test]
    fn split_routes_fallback_is_network_not_host() {
        let tunnel = WgTunnel {
            id: Uuid::new_v4(),
            name: "wg0".into(),
            interface: crate::types::Interface("wg0".into()),
            private_key: "x".into(),
            public_key: "y".into(),
            listen_port: 51820,
            address: Address::Network("172.29.240.1".parse().unwrap(), 24),
            dns: None,
            mtu: None,
            listen_interface: None,
            split_routes: None,
            status: VpnStatus::Down,
            created_at: Utc::now(),
            updated_at: Utc::now(),
        };
        let peer = WgPeer {
            id: Uuid::new_v4(),
            tunnel_id: tunnel.id,
            name: "peer1".into(),
            public_key: "pk".into(),
            preshared_key: None,
            client_private_key: Some("cpk".into()),
            endpoint: None,
            allowed_ips: vec![Address::Network("172.29.240.2".parse().unwrap(), 32)],
            persistent_keepalive: None,
            created_at: Utc::now(),
            updated_at: Utc::now(),
        };
        let cfg = peer.to_client_config(&tunnel, "1.2.3.4", true);
        assert!(cfg.contains("AllowedIPs = 172.29.240.0/24"));
        assert!(!cfg.contains("172.29.240.1/24"));
    }
}
