#!/bin/sh
#
# PROVIDE: rdns
# REQUIRE: NETWORKING
# KEYWORD: shutdown
#
# Add the following lines to /etc/rc.conf to enable rdns:
#   rdns_enable="YES"

. /etc/rc.subr

name="rdns"
rcvar="rdns_enable"

load_rc_config $name

: ${rdns_enable:="NO"}
: ${rdns_config:="/usr/local/etc/rdns/rdns.toml"}
: ${rdns_pidfile:="/var/run/rdns/rdns.pid"}

pidfile="${rdns_pidfile}"
procname="/usr/local/sbin/rdns"
command="/usr/sbin/daemon"
command_args="-f -p ${rdns_pidfile} -R 5 -S -T rdns -o /var/log/rdns/rdns.log ${procname} -c ${rdns_config}"

start_precmd="rdns_precmd"
stop_postcmd="rdns_poststop"

rdns_precmd()
{
    /bin/mkdir -p /var/run/rdns /usr/local/etc/rdns/zones /usr/local/etc/rdns/rpz
    /bin/rm -f ${rdns_pidfile}
}

rdns_poststop()
{
    /bin/rm -f ${rdns_pidfile}
}

run_rc_command "$1"
