#!/bin/sh
#
# PROVIDE: rtime
# REQUIRE: NETWORKING
# KEYWORD: shutdown
#
# Add the following lines to /etc/rc.conf to enable rtime:
#   rtime_enable="YES"

. /etc/rc.subr

name="rtime"
rcvar="rtime_enable"

load_rc_config $name

: ${rtime_enable:="NO"}
: ${rtime_config:="/usr/local/etc/rtime/rtime.toml"}
: ${rtime_pidfile:="/var/run/rtime/rtime.pid"}

pidfile="${rtime_pidfile}"
procname="/usr/local/sbin/rtime"
command="/usr/sbin/daemon"
command_args="-f -p ${rtime_pidfile} -R 5 -S -T rtime -o /var/log/rtime/rtime.log ${procname} --config ${rtime_config}"

start_precmd="rtime_precmd"
stop_postcmd="rtime_poststop"

rtime_precmd()
{
    /bin/mkdir -p /var/run/rtime /var/log/rtime /usr/local/etc/rtime
    /bin/rm -f ${rtime_pidfile}
}

rtime_poststop()
{
    /bin/rm -f ${rtime_pidfile}
}

run_rc_command "$1"
