[package]
name = "aifw-common"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
serde = { workspace = true }
serde_json = { workspace = true }
chrono = { workspace = true }
uuid = { workspace = true }
thiserror = { workspace = true }
sqlx = { workspace = true }
tokio = { workspace = true, features = ["sync", "net", "rt", "macros", "time", "io-util"] }
arc-swap = "1"
tracing = { workspace = true }
argon2 = { workspace = true }
tracing-subscriber = { workspace = true }
url = { workspace = true }
x25519-dalek = { workspace = true }
getrandom = { workspace = true }

[target.'cfg(unix)'.dependencies]
nix = { workspace = true }

[lints]
workspace = true
