[package]
name = "aifw-core"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
aifw-common = { workspace = true }
aifw-pf = { workspace = true }
tokio = { workspace = true, features = ["rt", "sync", "time", "net", "io-util", "fs", "process", "macros"] }
sqlx = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
thiserror = { workspace = true }
tracing = { workspace = true }
chrono = { workspace = true }
uuid = { workspace = true }
async-trait = { workspace = true }
sha2 = { workspace = true }
hex = { workspace = true }
aws-lc-rs = { workspace = true }
base64 = { workspace = true }
getrandom = { workspace = true }
cron = "0.17"
arc-swap = "1"
ip_network = "0.4"
ip_network_table = "0.2"
aws-credential-types = "1"
instant-acme = "0.8"
rcgen = { workspace = true }
reqwest = { workspace = true }
rustls = { workspace = true }
rustls-pemfile = { workspace = true }
lettre = { version = "0.11", default-features = false, features = ["tokio1-rustls-tls", "smtp-transport", "builder", "hostname"] }
rusty-s3 = "0.10"
aws-sigv4 = { version = "1", default-features = false, features = ["sign-http", "http1"] }
quick-xml = { version = "0.41", features = ["serialize"] }
url = "2"

[dev-dependencies]
anyhow = { workspace = true }
tokio-rustls = { workspace = true }

[lints]
workspace = true
